### PR TITLE
Try removing the no-audio flag from the emulator.

### PR DESCRIPTION
**Pull request by jaydeetay**

### CODE REVIEW

**Comment by barbeau** [comment]
@jaydeetay I've been struggling to get tests running on the emulator on Travis too. Here's the latest AFAIK:
https://github.com/OneBusAway/onebusaway-android/issues/720

I still haven't found the magical incantation to make it work though :(...

**Comment by jaydeetay** [comment]
Hey Sean! Good to hear from you, and thanks for the tips.  I'm at the
try-plausible-things-from-stackoverflow-till-it-works stage right now.

**Comment by barbeau** [comment]
🤞 that you hit it. Here's my most recent try in a PR if it helps... https://github.com/OneBusAway/onebusaway-android/pull/721

**Comment by barbeau** [comment]
What I should really do is just install Travis CI as a local Docker instance (https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e) and then hammer away at it. The killer part of testing is waiting forever for each build to fail...

**Comment by jaydeetay** [comment]
Obsolete

**Pull request closed without merging**
