### PR TITLE
Steal Sean's travis configuration

### PR DESCRIPTION
**Pull request by jaydeetay**

### CODE REVIEW

**Comment by barbeau** [comment]
Yeah, submitting this as a PR was on my TODO list :).

As you see, it currently fails with:

>Tests on test(AVD) - 6.0 failed: Instrumentation run failed due to 'Process crashed.'
com.android.builder.testing.ConnectedDevice > No tests found.[test(AVD) - 6.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @ Test annotations).
:app:connectedDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/sky-map-team/stardroid/app/build/reports/androidTests/connected/index.html

I'm assuming this has something to do with the specific unit test setup for stardroid, but I haven't had a chance to look into it yet.  If you have any ideas what might be happening let me know.

**Comment by jaydeetay** [comment]
Doh!  I'd been meaning to get around to this and then saw you'd got a head
start.  I'll try to get it fixed then - I've been really lax with tests and
that's something I've been meaning to get on top of.

**Comment by barbeau** [comment]
Ok, cool!  Other potential wrinkle I've been dealing with is that if any tests rely on Google APIs or Google Play Services, there is currently a problem getting a working Google API emulator running on Travis.  I'm not sure if this impacts stardroid?

If it does, relevant issues are:

* Android-maps-utils - https://github.com/googlemaps/android-maps-utils/issues/284
* Travis - https://github.com/travis-ci/travis-ci/issues/6122

I believe we're stuck waiting on Travis for resolution, see that issue for latest.

**Comment by jaydeetay** [comment]
OK I've removed what I think was the failing test, so I'm going to merge this and see what happens.

**Pull request merged**
