### PR TITLE
Move search control bar out of time travel linear layout

### PR DESCRIPTION
**Pull request by mmw125**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Run the unit tests with `gradlew app:connectedGmsDebugAndroidTest` to make sure you didn't break anything (with an emulator running or phone connected)

- [X] If you have multiple commits please combine them into one commit by squashing them.

Screenshot_1603597294

### CODE REVIEW

**Comment by mmw125** [comment]
fixes #361

**Comment by jaydeetay** [comment]
Cheers!
Haven't tested it but I bet you have.

**Comment by mmw125** [comment]
I haven't tested it on a physical device, but it was working on the emulator.

**Comment by jaydeetay** [comment]
I tested after merging and it works great!

**Pull request merged**
