### PR TITLE
Refactor the data generation

### PR DESCRIPTION
**Pull request by jaydeetay**
This removes the circular dependency that made the app dependent on datafiles that were dependent on the app. Previously the app had to be built first, resource ids generated, the datafiles updated then the app rebuilt with the data files. This was so that the resource ids for all of the i18n strings could be properly embedded.

However it was super fragile. Add a resource and all the ids could change, causing mislabelled objects or, more often, crashes. Even different versions of the Android SDK seemed to be able to cause this. Ugly, brittle and dangerous to developers it had little to recommend it other than we knew no better at the time.

This is still quite ugly (the creation of a module to be included in the app containing the proto as well as the tools app reaching into that module to borrow a source file is not what I wanted), but should be less brittle. A missing resource will now result in an ugly "MISSING LABEL" label in the UI but should at least not crash.

### CODE REVIEW

**Comment by jaydeetay** [comment]
Fairly major change - will need some careful QA.

**Comment by jaydeetay** [comment]
Profiling shows no appreciable difference vs the old app. The new proto-lite library shrinks the app a tad.

**Comment by TacoTheDank** [comment]
Oh... oh yes... it's so beautiful! (^✧ ∇ ✧)^

**Comment by jaydeetay** [comment]
Hopefully it'll make life easier.  I'm seeing some crashes on some devices though due to the new protocol buffer library, so need to look into that.

**Comment by TacoTheDank** [comment]
@jaydeetay I'm able to get built APKs to launch now, so I can now get to testing the AndroidX Preference migration and fixing any crashes that appear before the PR is made. I'm actually making some progress on it now, but it requires kind of a large overhaul of class usages in the project. The settings will definitely look different for sure.

**Comment by jaydeetay** [comment]
Hi - I just want to caution about doing any major refactoring...I'm not
sure I want that at this stage. Our testing and QA isn't adequate right now
and I don't have the time to fix things if they go wrong.

**Comment by TacoTheDank** [comment]
@jaydeetay That's fine, I'm probably not going to make it anyway (it's too rough around the edges right now).

**Pull request merged**
