### PR TITLE
whatsnew update (+fa)

### PR DESCRIPTION
**Pull request by VegaDark**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `gradlew app:connectedGmsDebugAndroidTest` to make sure you didn't break anything (with an emulator running or phone connected)

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by jaydeetay** [comment]
Thanks!  It's likely there'll be other updates before I release this version. What's a good way to handle this so you don't have to translate this file repeatedly? Of course, if you don't mind doing it this way that's fine too.

**Comment by VegaDark** [comment]
Well I can update it anytime I get a notification, I have no problem in doing this, but also I can wait before its final release, just that I have to guess when it will happen :p

**Comment by VegaDark** [comment]
> Thanks! It's likely there'll be other updates before I release this version. What's a good way to handle this so you don't have to translate this file repeatedly? Of course, if you don't mind doing it this way that's fine too.

Well I can update it anytime I get a notification, I have no problem in doing this, but also I can wait before its final release, just that I have to guess when it will happen :p

**Comment by jaydeetay** [comment]
OK I'll try to 'batch' my changes to that file so that you're not pinged
too often.  Thanks again for your work.

John

**Pull request merged**
