### PR TITLE
Changes in search control bar

### LINKED ISSUE #252: UI glitch in the search screen
**Summary:** 

The Exit Button of Search Screen overlaps with the screen of base activity making it difficult to close the search layer.

**Steps to reproduce:** 

To fix the issue the menu should move lower, so that button is not overlapping with the menu of base activity

**Device and Android version:** 
I encountered this issue on MI A2, Android version 9, API level 28

**Screenshots:** 

image
image

### PR DESCRIPTION
**Pull request by sashrikakaur**
Signed-off-by: Sashrika Kaur <sashrikakaur@yahoo.co.in>

Fixes #252 

The cancel search button was overlapping with the sky map toolbar. Adding a margin prevents the overlap and allows easy access of the menu in skymap toolbar and search button in the search control bar.

ezgif com-video-to-gif

### CODE REVIEW

**Comment by tavishjain** [comment]
This is a really bad implementation of how you have fixed the code. Simply giving a padding to the app bar doesn't completely fix this issue and cannot be considered as a fix.

**Comment by jaydeetay** [comment]
Thanks for the fix @sashrikakaur .  It looks like there's a conflict in gradle.xml - can you remove that file from the PR?  We have a separate task add this file to .gitignore.

@tavishjain can you explain your objections a little more? At first glance this looks like a reasonable fix.

**Comment by tavishjain** [comment]
@jaydeetay  this shifting of the app bar is not the exact fix for this issue. We will have to use CoordinatorLayout so that on press on the screen, the app bar moves down and on tapping again, it moves back up

**Comment by jaydeetay** [comment]
We certainly could do that. It's not obvious to me why having the search
controls stay in the same spot would be inherently bad though.

**Comment by tavishjain** [comment]
@jaydeetay it is not bad that the search controls remain in the same place, but it provides a bad UX. Having a free space abbove the app bar (the one in Red colour) doesnt reallly seem to be good. 
Untitled

**Comment by sashrikakaur** [comment]
Considering sky map uses OpenGL ES to render views adding a padding doesn't necessarily mean a bad UI as the whole view is used in the app to display celestial objects and so does the space above the screen. 
Hence, I think this would be a good fix as the space present is not empty it still renders a view.
Let me know if you have an alternate solution @jaydeetay @tavishjain , I'll be happy to hear your implementation for the same!

**Comment by sashrikakaur** [comment]
@jaydeetay , I've resolved the conflict, let me know if everything looks good now.

**Comment by sashrikakaur** [comment]
closed in favor of #264

**Pull request closed without merging**
